package ca.uwaterloo.ece452.discoveruwaterloo.data

import java.util.Calendar

enum class RepeatOption { NONE, DAILY, WEEKLY, MONTHLY }

// Cron day-of-week follows the standard convention: 0 or 7 = Sunday, 1 = Monday, ..., 6 = Saturday.
// Calendar.DAY_OF_WEEK uses SUNDAY = 1 .. SATURDAY = 7, so subtracting 1 converts it directly.
private fun cronDayOfWeek(calendar: Calendar): Int = calendar.get(Calendar.DAY_OF_WEEK) - 1

fun cronForRepeatOption(option: RepeatOption, start: Calendar): String? {
    val minute = start.get(Calendar.MINUTE)
    val hour = start.get(Calendar.HOUR_OF_DAY)
    return when (option) {
        RepeatOption.NONE -> null
        RepeatOption.DAILY -> "$minute $hour * * *"
        RepeatOption.WEEKLY -> "$minute $hour * * ${cronDayOfWeek(start)}"
        RepeatOption.MONTHLY -> "$minute $hour ${start.get(Calendar.DAY_OF_MONTH)} * *"
    }
}

// Best-effort human label for a cron string generated by cronForRepeatOption.
// Returns null for a one-time event (no schedule).
fun repeatLabel(schedule: String?): String? {
    if (schedule == null) return null
    val fields = schedule.trim().split(Regex("\\s+"))
    if (fields.size != 5) return null
    val dayOfMonth = fields[2]
    val dayOfWeek = fields[4]
    return when {
        dayOfMonth != "*" -> "Monthly"
        dayOfWeek != "*" -> "Weekly"
        else -> "Daily"
    }
}
