"""add lat lng to event

Revision ID: 985a12372678
Revises: 0002
Create Date: 2026-06-13 19:56:47.210913

"""
from alembic import op
import sqlalchemy as sa


revision = '985a12372678'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('lng', sa.Float(), nullable=True))
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_column('events', 'lng')
    op.drop_column('events', 'lat')
    # ### end Alembic commands ###
